name: Windows Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    env:
      VCPKG_BINARY_SOURCES: clear;x-gha,readwrite
      VCPKG_FEATURE_FLAGS: manifests,registries,binarycaching

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Ensure Ninja is available
        uses: seanmiddleditch/gha-setup-ninja@v1

      - name: Install and build via run.bat
        shell: cmd
        run: |
          call run.bat --ci --skip-run --no-shortcut

      - name: Run ctest
        shell: cmd
        run: |
          cd build
          ctest --build-config RelWithDebInfo --output-on-failure
