name: Windows Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    env:
      VCPKG_BINARY_SOURCES: clear;x-gha,readwrite
      VCPKG_FEATURE_FLAGS: manifests,registries,binarycaching
      VCPKG_CMAKE_GENERATOR: 'Visual Studio 17 2022'
      VCPKG_CMAKE_GENERATOR_PLATFORM: x64
      VCPKG_CMAKE_GENERATOR_TOOLSET: v143
      VCPKG_PREFER_NINJA: '0'

    steps:
      - uses: actions/checkout@v4

      - name: Set up vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgJsonGlob: 'vcpkg.json'

      - name: Configure CMake
        shell: pwsh
        run: >
          cmake -S . -B build
          -G "Visual Studio 17 2022"
          -A x64
          -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_ROOT\scripts\buildsystems\vcpkg.cmake"
          -DCMAKE_BUILD_TYPE=RelWithDebInfo
          -DCMAKE_RUNTIME_OUTPUT_DIRECTORY="${{ github.workspace }}\ENGINE"

      - name: Build
        shell: pwsh
        run: cmake --build build --config RelWithDebInfo

      - name: Run ctest
        shell: pwsh
        working-directory: build
        run: ctest -C RelWithDebInfo --output-on-failure

      - name: Upload engine.exe
        uses: actions/upload-artifact@v4
        with:
          name: engine-windows
          path: ENGINE/engine.exe
